// <auto-generated />
namespace Ahorcado_Grupo5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AgregaAvatarAJugador : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregaAvatarAJugador));
        
        string IMigrationMetadata.Id
        {
            get { return "202508060637535_AgregaAvatarAJugador"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
